from typing import overload

class vec2:
    x: float
    y: float
    def __init__(self, x: float, y: float) -> None: ...
    def __add__(self, other: "vec2") -> "vec2": ...
    def __sub__(self, other: "vec2") -> "vec2": ...
    def __mul__(self, scalar: float) -> "vec2": ...
    def __rmul__(self, scalar: float) -> "vec2": ...
    def __truediv__(self, scalar: float) -> "vec2": ...
    def __eq__(self, other: object) -> bool: ...
    def length(self) -> float: ...
    def normalize(self) -> "vec2": ...
    def xAngle(self) -> float: ...

class mat2:
    m: list[list[float]]
    def __init__(self, a: float, b: float, c: float, d: float) -> None: ...
    @staticmethod
    def rotation(angle: float) -> "mat2": ...
    def identity(self) -> "mat2": ...
    def __repr__(self) -> str: ...
    @overload
    def __mul__(self, other: "mat2") -> "mat2": ...
    @overload
    def __mul__(self, other: vec2) -> vec2: ...
    @overload
    def __mul__(self, other: float) -> "mat2": ...
    def __rmul__(self, other: float) -> "mat2": ...
    def det(self) -> float: ...
    def transpose(self) -> "mat2": ...
    def adj(self) -> "mat2": ...
    def inverse(self) -> "mat2": ...

def generateBezierCurve(p0: vec2, p1: vec2, p2: vec2, p3: vec2, num_points: int = ...) -> list[vec2]: ...

def bezier(t: float, p0: vec2, p1: vec2, p2: vec2, p3: vec2) -> vec2: ...

def sign(x: float) -> int: ...

def clamp(x: float, minVal: float, maxVal: float) -> float: ...

def maxV(x: float, v: float) -> float: ...

def minV(x: float, v: float) -> float: ...

def avr(*x: float) -> float: ...

def angleDiff(a: float, b: float) -> float: ...